---
title: "Honda_Project1_Offical"
author: "Deepesh Giri, Jonathan Levy, Lexie Cohen, Yang Zeng"
date: "2025-01-28"
output: html_document
---

## Libraries

```{r}
library(readr)
library(tidyverse)
library(ggplot2)
```

## Load data from CSV file

```{r}
savings <- read_csv("Saving_Values_updated.csv")
sourcing <- read_csv("Sourceing Data.csv")
task <- read_csv("Task Data.csv")
```


```{r}

# filter savings projects by unique project id
unique_savings_PID <- unique(savings$`[SFM]Project (Project Id)`)

# get savings data fram where the unique savings id matches the above list
unique_sourcing_data <- sourcing %>% filter(`[SPRJ]Project (Project Id)` %in% unique_savings_PID)


# select columns that we want to look at
unique_sourcing_data <- unique_sourcing_data %>% select( `[SPRJ]Project (Project Id)`, `Baseline Spend`,
                                `Savings`, `[SPRJ] Project Reason`, `[SPRJ] Spend Level`,
                                `[SPRJ]Commodity (Commodity)`, `[SPRJ]Owner (User)`
)

# Rename columns to be easier to refrence and interpret
unique_sourcing_data <- unique_sourcing_data %>% rename(
  pid =  `[SPRJ]Project (Project Id)`,
  budget = `Baseline Spend`,
  project_reason = `[SPRJ] Project Reason`,
  spend_level = `[SPRJ] Spend Level`,
  product_purchased = `[SPRJ]Commodity (Commodity)`, 
  employee = `[SPRJ]Owner (User)`
)

# Remove $ and commas, and transform into numeric columns
unique_sourcing_data <- unique_sourcing_data %>%
  mutate(cleaned_budget = as.numeric(gsub("[$,]", "", budget)),
         cleaned_savings = as.numeric(gsub("[$,]", "", Savings))) %>%
  select(-budget, -Savings) %>%
  rename(budget = cleaned_budget, savings = cleaned_savings)


# Calculate savings_ratio and handle NAs
unique_sourcing_data <- unique_sourcing_data %>%
  mutate(savings_ratio = ifelse(is.na(savings) | is.na(budget), NA, savings / budget))

# Create posotive_savings column indicating if savings are positive
unique_sourcing_data <- unique_sourcing_data %>%
  mutate(positive_savings = ifelse(savings > 0, TRUE, FALSE))

```
## seperate project tasks by task name

```{r}
# rename columns for easier references later
task <- task %>% rename(
  pid = `Project - Project Id`,
  task_name = `Task Name - Task Name`
)

# crease phase 1 and phase 2 task subsets where the task names are the required tasks
phase1 <- task %>% filter(task_name == "Obtain Final SOW - Sourcing Clock Starts")
phase2 <- task %>% filter(task_name == "Sourcing Complete - Sourcing Clock Stops")

```
